version: '3.5'

services:
  laravel-app:
    build: .
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3307"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: