version: '3'
services:

  #Laravel App
  avenco:
    build:
      context: .
      dockerfile: Dockerfile
    image: avenco
    container_name: avenco
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: avenco
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - avenco_network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.d/:/etc/nginx/conf.d/
    networks:
      - avenco_network

  #MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3309"
    environment:
      MYSQL_DATABASE: avenco
      MYSQL_USER: root
      MYSQL_PASSWORD: root031995
      MYSQL_ROOT_PASSWORD: root031995
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - avenco_network

#Docker Networks
networks:
  avenco_network:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local  