version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/src/app
    ports:
      - "8080:80"
    links:
      - php
    depends_on:
      - mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src/app
    environment:
        XDEBUG_MODE: debug
        XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
        DB_PORT: 3306
        DB_HOST: mysql
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none' 
    ports:
      - 1025:1025 
      - 8025:8025 
volumes:
  mysqldata:
